import { createFileRoute } from "@tanstack/react-router";
import { pageHead } from "@/lib/pravaah/head";
import { ALERTS } from "@/lib/pravaah/demo-data";
import { DemoBanner, PageHeader, Panel, RiskBadge } from "@/components/pravaah/primitives";

export const Route = createFileRoute("/alerts")({
  head: pageHead(
    "Alerts",
    "Simulation alerts generated by the PRAVAAH prototype risk engine, with hazard type, alert level and recommended action.",
  ),
  component: AlertsPage,
});

function AlertsPage() {
  return (
    <>
      <PageHeader
        title="Alerts"
        subtitle="Every alert below is a SIMULATION produced by the prototype engine. No message is dispatched to any real emergency channel."
      />
      <DemoBanner text="Alerts are simulated. PRAVAAH is not connected to NDMA SACHET or any dissemination system." />

      <div className="grid gap-3 lg:grid-cols-2">
        {ALERTS.map((a) => (
          <Panel key={a.id}>
            <div className="flex flex-wrap items-start justify-between gap-2">
              <div>
                <p className="label-mono">{a.alert_level} · {a.hazard_type.replace("_", " ")}</p>
                <h3 className="mt-1 font-semibold">{a.title}</h3>
                <p className="text-sm text-muted-foreground">{a.location}</p>
              </div>
              <RiskBadge level={a.risk_level} />
            </div>
            <p className="mt-3 text-sm">{a.message}</p>
            <div className="mt-3 grid grid-cols-2 gap-2 text-xs text-muted-foreground">
              <span>Issued: {new Date(a.created_at).toLocaleString()}</span>
              <span>Expires: {new Date(a.expires_at).toLocaleString()}</span>
              <span>Status: {a.status}</span>
              <span>By: {a.created_by}</span>
            </div>
          </Panel>
        ))}
      </div>

      <Panel title="Alert level definitions">
        <ul className="grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-5">
          {[
            ["INFO", "Situational information, no action required."],
            ["ADVISORY", "Be aware; conditions may change."],
            ["WATCH", "Conditions favourable for a hazard; prepare."],
            ["WARNING", "Hazard likely or occurring; act now."],
            ["EMERGENCY", "Severe threat to life; immediate protective action."],
          ].map(([k, v]) => (
            <li key={k} className="rounded-md border border-border p-2.5">
              <p className="label-mono">{k}</p>
              <p className="mt-1 text-xs text-muted-foreground">{v}</p>
            </li>
          ))}
        </ul>
      </Panel>
    </>
  );
}
