import type {
  Alert,
  DataSourceStatus,
  DisasterEvent,
  DistrictLocation,
  Incident,
  InfrastructureAsset,
} from "./types";

export const DEMO_NOTICE =
  "DEMO / SIMULATION DATA — values are synthetic and generated for demonstration only.";

export const DISTRICTS: DistrictLocation[] = [
  {
    id: "utk-chamoli",
    name: "Chamoli",
    state: "Uttarakhand",
    lat: 30.4,
    lng: 79.32,
    population: 391605,
    radius_km: 22,
    primary_hazards: ["LANDSLIDE", "FLASH_FLOOD", "GLOF"],
    signals: {
      rainfall_mm_24h: 168,
      soil_moisture_pct: 82,
      river_level_pct: 74,
      slope_deg: 38,
      elevation_m: 2100,
      historical_events: 14,
      temperature_c: 17,
      population_density: 49,
      infrastructure_density: 62,
      river_blockage_index: 0.71,
      snowpack_index: 0.55,
    },
    is_demo: true,
  },
  {
    id: "utk-rudraprayag",
    name: "Rudraprayag",
    state: "Uttarakhand",
    lat: 30.28,
    lng: 78.98,
    population: 242285,
    radius_km: 18,
    primary_hazards: ["LANDSLIDE", "FLASH_FLOOD"],
    signals: {
      rainfall_mm_24h: 121,
      soil_moisture_pct: 74,
      river_level_pct: 66,
      slope_deg: 34,
      elevation_m: 1450,
      historical_events: 11,
      temperature_c: 19,
      population_density: 122,
      infrastructure_density: 54,
      river_blockage_index: 0.48,
      snowpack_index: 0.3,
    },
    is_demo: true,
  },
  {
    id: "hp-kullu",
    name: "Kullu",
    state: "Himachal Pradesh",
    lat: 31.96,
    lng: 77.11,
    population: 437903,
    radius_km: 25,
    primary_hazards: ["CLOUDBURST", "LANDSLIDE", "FLASH_FLOOD"],
    signals: {
      rainfall_mm_24h: 142,
      soil_moisture_pct: 78,
      river_level_pct: 69,
      slope_deg: 33,
      elevation_m: 1279,
      historical_events: 13,
      temperature_c: 21,
      population_density: 80,
      infrastructure_density: 71,
      river_blockage_index: 0.42,
      snowpack_index: 0.4,
    },
    is_demo: true,
  },
  {
    id: "hp-kinnaur",
    name: "Kinnaur",
    state: "Himachal Pradesh",
    lat: 31.58,
    lng: 78.44,
    population: 84121,
    radius_km: 28,
    primary_hazards: ["LANDSLIDE", "AVALANCHE"],
    signals: {
      rainfall_mm_24h: 58,
      soil_moisture_pct: 51,
      river_level_pct: 45,
      slope_deg: 42,
      elevation_m: 3100,
      historical_events: 9,
      temperature_c: 9,
      population_density: 13,
      infrastructure_density: 28,
      river_blockage_index: 0.33,
      snowpack_index: 0.78,
    },
    is_demo: true,
  },
  {
    id: "sk-mangan",
    name: "Mangan (North Sikkim)",
    state: "Sikkim",
    lat: 27.51,
    lng: 88.53,
    population: 43709,
    radius_km: 30,
    primary_hazards: ["GLOF", "LANDSLIDE", "FLASH_FLOOD"],
    signals: {
      rainfall_mm_24h: 96,
      soil_moisture_pct: 69,
      river_level_pct: 81,
      slope_deg: 40,
      elevation_m: 1900,
      historical_events: 8,
      temperature_c: 14,
      population_density: 10,
      infrastructure_density: 24,
      river_blockage_index: 0.64,
      snowpack_index: 0.68,
    },
    is_demo: true,
  },
  {
    id: "as-dhemaji",
    name: "Dhemaji",
    state: "Assam",
    lat: 27.48,
    lng: 94.58,
    population: 686133,
    radius_km: 34,
    primary_hazards: ["FLOOD"],
    signals: {
      rainfall_mm_24h: 112,
      soil_moisture_pct: 88,
      river_level_pct: 92,
      slope_deg: 4,
      elevation_m: 96,
      historical_events: 21,
      temperature_c: 29,
      population_density: 214,
      infrastructure_density: 58,
      river_blockage_index: 0.22,
      snowpack_index: 0,
    },
    is_demo: true,
  },
  {
    id: "as-barpeta",
    name: "Barpeta",
    state: "Assam",
    lat: 26.32,
    lng: 91.0,
    population: 1693622,
    radius_km: 30,
    primary_hazards: ["FLOOD"],
    signals: {
      rainfall_mm_24h: 74,
      soil_moisture_pct: 79,
      river_level_pct: 76,
      slope_deg: 3,
      elevation_m: 35,
      historical_events: 19,
      temperature_c: 31,
      population_density: 632,
      infrastructure_density: 66,
      river_blockage_index: 0.18,
      snowpack_index: 0,
    },
    is_demo: true,
  },
  {
    id: "ml-east-khasi",
    name: "East Khasi Hills",
    state: "Meghalaya",
    lat: 25.45,
    lng: 91.75,
    population: 825922,
    radius_km: 26,
    primary_hazards: ["LANDSLIDE", "FLASH_FLOOD"],
    signals: {
      rainfall_mm_24h: 205,
      soil_moisture_pct: 84,
      river_level_pct: 58,
      slope_deg: 27,
      elevation_m: 1496,
      historical_events: 10,
      temperature_c: 22,
      population_density: 293,
      infrastructure_density: 63,
      river_blockage_index: 0.27,
      snowpack_index: 0,
    },
    is_demo: true,
  },
  {
    id: "ar-upper-siang",
    name: "Upper Siang",
    state: "Arunachal Pradesh",
    lat: 28.63,
    lng: 94.98,
    population: 35320,
    radius_km: 35,
    primary_hazards: ["LANDSLIDE", "FLASH_FLOOD"],
    signals: {
      rainfall_mm_24h: 88,
      soil_moisture_pct: 71,
      river_level_pct: 63,
      slope_deg: 36,
      elevation_m: 1800,
      historical_events: 6,
      temperature_c: 18,
      population_density: 7,
      infrastructure_density: 15,
      river_blockage_index: 0.45,
      snowpack_index: 0.35,
    },
    is_demo: true,
  },
  {
    id: "jk-ramban",
    name: "Ramban",
    state: "Jammu & Kashmir",
    lat: 33.24,
    lng: 75.24,
    population: 283313,
    radius_km: 20,
    primary_hazards: ["LANDSLIDE"],
    signals: {
      rainfall_mm_24h: 64,
      soil_moisture_pct: 58,
      river_level_pct: 41,
      slope_deg: 39,
      elevation_m: 1200,
      historical_events: 12,
      temperature_c: 20,
      population_density: 179,
      infrastructure_density: 44,
      river_blockage_index: 0.38,
      snowpack_index: 0.25,
    },
    is_demo: true,
  },
  {
    id: "utk-pithoragarh",
    name: "Pithoragarh",
    state: "Uttarakhand",
    lat: 29.58,
    lng: 80.22,
    population: 483439,
    radius_km: 26,
    primary_hazards: ["LANDSLIDE", "CLOUDBURST"],
    signals: {
      rainfall_mm_24h: 44,
      soil_moisture_pct: 46,
      river_level_pct: 38,
      slope_deg: 31,
      elevation_m: 1627,
      historical_events: 9,
      temperature_c: 22,
      population_density: 68,
      infrastructure_density: 40,
      river_blockage_index: 0.2,
      snowpack_index: 0.2,
    },
    is_demo: true,
  },
  {
    id: "ml-west-garo",
    name: "West Garo Hills",
    state: "Meghalaya",
    lat: 25.52,
    lng: 90.22,
    population: 643291,
    radius_km: 28,
    primary_hazards: ["FLOOD", "LANDSLIDE"],
    signals: {
      rainfall_mm_24h: 39,
      soil_moisture_pct: 44,
      river_level_pct: 36,
      slope_deg: 18,
      elevation_m: 450,
      historical_events: 5,
      temperature_c: 27,
      population_density: 152,
      infrastructure_density: 37,
      river_blockage_index: 0.12,
      snowpack_index: 0,
    },
    is_demo: true,
  },
];

export const INFRASTRUCTURE: InfrastructureAsset[] = [
  ["utk-chamoli", "District Hospital Gopeshwar", "HOSPITAL", 30.41, 79.33, "AT_RISK", 120000],
  ["utk-chamoli", "Joshimath–Badrinath Highway Bridge", "BRIDGE", 30.55, 79.56, "AT_RISK", 80000],
  ["utk-chamoli", "Tapovan Power Station (demo)", "POWER", 30.49, 79.6, "DISRUPTED", 210000],
  ["utk-chamoli", "GIC Gopeshwar Shelter", "SHELTER", 30.4, 79.31, "OPERATIONAL", 4200],
  ["utk-rudraprayag", "CHC Rudraprayag", "HOSPITAL", 30.29, 78.98, "OPERATIONAL", 60000],
  ["utk-rudraprayag", "Alaknanda Road Bridge", "BRIDGE", 30.29, 78.98, "AT_RISK", 45000],
  ["hp-kullu", "Regional Hospital Kullu", "HOSPITAL", 31.96, 77.11, "OPERATIONAL", 180000],
  ["hp-kullu", "NH-3 Manali Corridor", "ROAD", 31.99, 77.13, "AT_RISK", 300000],
  ["hp-kullu", "Kullu Fire Station", "FIRE", 31.95, 77.1, "OPERATIONAL", 150000],
  ["hp-kinnaur", "Reckong Peo Police Station", "POLICE", 31.54, 78.27, "OPERATIONAL", 30000],
  ["sk-mangan", "Mangan District Hospital", "HOSPITAL", 27.51, 88.53, "AT_RISK", 40000],
  ["sk-mangan", "Teesta Stage-III Power (demo)", "POWER", 27.46, 88.5, "AT_RISK", 90000],
  ["as-dhemaji", "Dhemaji Civil Hospital", "HOSPITAL", 27.48, 94.58, "OPERATIONAL", 250000],
  ["as-dhemaji", "Brahmaputra Embankment Road", "ROAD", 27.42, 94.6, "DISRUPTED", 400000],
  ["as-dhemaji", "Silapathar Relief Shelter", "SHELTER", 27.51, 94.62, "OPERATIONAL", 9000],
  ["as-barpeta", "Barpeta Railway Halt", "RAILWAY", 26.32, 91.0, "AT_RISK", 220000],
  ["as-barpeta", "Barpeta Model Shelter", "SHELTER", 26.33, 91.02, "OPERATIONAL", 7500],
  ["ml-east-khasi", "Shillong Civil Hospital", "HOSPITAL", 25.57, 91.88, "OPERATIONAL", 350000],
  ["ml-east-khasi", "Sohra Road Cutting", "ROAD", 25.28, 91.72, "AT_RISK", 60000],
  ["ar-upper-siang", "Yingkiong PHC", "HOSPITAL", 28.63, 94.98, "OPERATIONAL", 20000],
  ["jk-ramban", "NH-44 Ramban Stretch", "ROAD", 33.24, 75.24, "AT_RISK", 500000],
  ["jk-ramban", "Ramban Higher Secondary School", "SCHOOL", 33.25, 75.25, "OPERATIONAL", 3000],
  ["utk-pithoragarh", "Pithoragarh District Hospital", "HOSPITAL", 29.58, 80.22, "OPERATIONAL", 140000],
  ["ml-west-garo", "Tura Civil Hospital", "HOSPITAL", 25.51, 90.21, "OPERATIONAL", 160000],
].map(([district_id, name, type, lat, lng, status, served], i) => ({
  id: `infra-${i + 1}`,
  district_id: district_id as string,
  name: name as string,
  type: type as InfrastructureAsset["type"],
  lat: lat as number,
  lng: lng as number,
  status: status as InfrastructureAsset["status"],
  population_served: served as number,
  is_demo: true as const,
}));

export const HISTORICAL_EVENTS: DisasterEvent[] = [
  {
    id: "ev-1",
    event_type: "FLASH_FLOOD",
    location: "Kedarnath, Rudraprayag",
    state: "Uttarakhand",
    lat: 30.73,
    lng: 79.07,
    date: "2013-06-16",
    severity: "EXTREME",
    fatalities: null,
    affected_population: null,
    rainfall_mm: null,
    source: "Widely documented public record",
    description:
      "Extreme rainfall combined with a moraine-dammed lake breach produced catastrophic flash flooding in the Mandakini valley. Figures intentionally omitted — consult official reports.",
    is_demo: false,
  },
  {
    id: "ev-2",
    event_type: "LANDSLIDE",
    location: "Chamoli (Rishiganga valley)",
    state: "Uttarakhand",
    lat: 30.49,
    lng: 79.6,
    date: "2021-02-07",
    severity: "EXTREME",
    fatalities: null,
    affected_population: null,
    rainfall_mm: null,
    source: "Widely documented public record",
    description:
      "A rock-ice avalanche generated a debris flow that damaged hydropower infrastructure downstream — a textbook cascading Himalayan hazard.",
    is_demo: false,
  },
  {
    id: "ev-3",
    event_type: "GLOF",
    location: "South Lhonak Lake / Teesta basin",
    state: "Sikkim",
    lat: 27.91,
    lng: 88.2,
    date: "2023-10-04",
    severity: "EXTREME",
    fatalities: null,
    affected_population: null,
    rainfall_mm: null,
    source: "Widely documented public record",
    description:
      "A glacial lake outburst propagated down the Teesta, damaging dams, bridges and roads across multiple districts.",
    is_demo: false,
  },
  {
    id: "ev-4",
    event_type: "FLOOD",
    location: "Dhemaji (Brahmaputra basin)",
    state: "Assam",
    lat: 27.48,
    lng: 94.58,
    date: "2024-07-02",
    severity: "HIGH",
    fatalities: null,
    affected_population: 180000,
    rainfall_mm: 118,
    source: "DEMO record",
    description: "Demonstration record of a monsoon flood wave used to exercise the risk engine.",
    is_demo: true,
  },
  {
    id: "ev-5",
    event_type: "CLOUDBURST",
    location: "Kullu valley",
    state: "Himachal Pradesh",
    lat: 31.96,
    lng: 77.11,
    date: "2023-08-14",
    severity: "HIGH",
    fatalities: null,
    affected_population: null,
    rainfall_mm: null,
    source: "Widely documented public record",
    description:
      "Localised extreme rainfall triggered debris flows along the Beas, cutting the NH-3 corridor.",
    is_demo: false,
  },
  {
    id: "ev-6",
    event_type: "LANDSLIDE",
    location: "East Khasi Hills",
    state: "Meghalaya",
    lat: 25.45,
    lng: 91.75,
    date: "2025-06-18",
    severity: "MODERATE",
    fatalities: null,
    affected_population: 24000,
    rainfall_mm: 214,
    source: "DEMO record",
    description: "Demonstration record of slope failures after sustained orographic rainfall.",
    is_demo: true,
  },
];

export const ALERTS: Alert[] = [
  {
    id: "alert-1",
    title: "SIMULATION ALERT — Extreme landslide & flash-flood risk",
    hazard_type: "MULTI_HAZARD",
    risk_level: "EXTREME",
    alert_level: "EMERGENCY",
    location: "Chamoli, Uttarakhand",
    message:
      "SIMULATION ALERT. Modelled cascade: saturated slopes → debris flow → partial channel blockage → downstream surge. Recommended action: evacuation preparation for valley-floor settlements and staging of response teams.",
    created_at: new Date(Date.now() - 42 * 60_000).toISOString(),
    expires_at: new Date(Date.now() + 10 * 3600_000).toISOString(),
    status: "ACTIVE",
    created_by: "district.authority@demo",
    is_simulation: true,
  },
  {
    id: "alert-2",
    title: "SIMULATION ALERT — River level approaching danger mark",
    hazard_type: "FLOOD",
    risk_level: "HIGH",
    alert_level: "WARNING",
    location: "Dhemaji, Assam",
    message:
      "SIMULATION ALERT. Modelled river stage at 92% of danger level with saturated soils. Recommended action: shelter readiness and embankment patrolling.",
    created_at: new Date(Date.now() - 3 * 3600_000).toISOString(),
    expires_at: new Date(Date.now() + 18 * 3600_000).toISOString(),
    status: "ACTIVE",
    created_by: "district.authority@demo",
    is_simulation: true,
  },
  {
    id: "alert-3",
    title: "SIMULATION ALERT — Heavy rainfall watch",
    hazard_type: "CLOUDBURST",
    risk_level: "HIGH",
    alert_level: "WATCH",
    location: "Kullu, Himachal Pradesh",
    message:
      "SIMULATION ALERT. Modelled convective rainfall over steep catchments. Recommended action: restrict night travel on the valley highway.",
    created_at: new Date(Date.now() - 7 * 3600_000).toISOString(),
    expires_at: new Date(Date.now() + 6 * 3600_000).toISOString(),
    status: "ACTIVE",
    created_by: "analyst@demo",
    is_simulation: true,
  },
  {
    id: "alert-4",
    title: "SIMULATION ALERT — GLOF monitoring advisory",
    hazard_type: "GLOF",
    risk_level: "MODERATE",
    alert_level: "ADVISORY",
    location: "Mangan, Sikkim",
    message:
      "SIMULATION ALERT. Elevated lake-level proxy and high channel occupancy. Recommended action: continued monitoring of upstream basin.",
    created_at: new Date(Date.now() - 26 * 3600_000).toISOString(),
    expires_at: new Date(Date.now() + 2 * 3600_000).toISOString(),
    status: "ACTIVE",
    created_by: "analyst@demo",
    is_simulation: true,
  },
];

export const INCIDENTS: Incident[] = [
  {
    id: "inc-1",
    title: "Road blockage — debris flow across valley highway",
    hazard_type: "LANDSLIDE",
    location: "Chamoli, Uttarakhand",
    reported_at: new Date(Date.now() - 90 * 60_000).toISOString(),
    severity: "HIGH",
    status: "RESPONDING",
    teams_assigned: 3,
    notes: "Two earth movers deployed. Alternate route advisory issued to travellers.",
    is_demo: true,
  },
  {
    id: "inc-2",
    title: "Embankment seepage reported by field sensor",
    hazard_type: "FLOOD",
    location: "Dhemaji, Assam",
    reported_at: new Date(Date.now() - 5 * 3600_000).toISOString(),
    severity: "MODERATE",
    status: "REPORTED",
    teams_assigned: 1,
    notes: "Awaiting engineering assessment.",
    is_demo: true,
  },
  {
    id: "inc-3",
    title: "Foot-bridge washed out in tributary surge",
    hazard_type: "FLASH_FLOOD",
    location: "Mangan, Sikkim",
    reported_at: new Date(Date.now() - 20 * 3600_000).toISOString(),
    severity: "HIGH",
    status: "CONTAINED",
    teams_assigned: 2,
    notes: "Temporary crossing established; 4 hamlets reconnected.",
    is_demo: true,
  },
  {
    id: "inc-4",
    title: "School building declared unsafe after slope crack",
    hazard_type: "LANDSLIDE",
    location: "Ramban, Jammu & Kashmir",
    reported_at: new Date(Date.now() - 52 * 3600_000).toISOString(),
    severity: "MODERATE",
    status: "CLOSED",
    teams_assigned: 1,
    notes: "Students relocated to community hall.",
    is_demo: true,
  },
];

export const DATA_SOURCES: DataSourceStatus[] = [
  {
    name: "IMD rainfall & nowcast",
    organisation: "India Meteorological Department",
    data_type: "Weather observations / forecasts",
    status: "INTEGRATION_PLANNED",
    last_updated: "—",
    notes: "Not connected. The WeatherProvider interface is ready for a real adapter.",
  },
  {
    name: "Bhuvan / ISRO geospatial products",
    organisation: "ISRO / NRSC",
    data_type: "Satellite imagery, landslide inventory",
    status: "REFERENCE",
    last_updated: "—",
    notes: "Used as a documented reference only. No live feed is connected.",
  },
  {
    name: "CWC river stage",
    organisation: "Central Water Commission",
    data_type: "Hydrological observations",
    status: "INTEGRATION_PLANNED",
    last_updated: "—",
    notes: "River-level values in this prototype are synthetic.",
  },
  {
    name: "NDMA SACHET",
    organisation: "NDMA",
    data_type: "Common alerting protocol ecosystem",
    status: "REFERENCE",
    last_updated: "—",
    notes: "Referenced as the target dissemination channel. No alerts are dispatched.",
  },
  {
    name: "PRAVAAH demo generator",
    organisation: "PRAVAAH AI (internal)",
    data_type: "Synthetic observations for all districts",
    status: "DEMO",
    last_updated: "live",
    notes: "Powers every number you see in this prototype.",
  },
  {
    name: "Prototype risk & cascade engine",
    organisation: "PRAVAAH AI (internal)",
    data_type: "Model outputs",
    status: "CONNECTED",
    last_updated: "live",
    notes: "Deterministic, explainable weighted model — see Model Performance.",
  },
];

export const DEMO_USERS = [
  { email: "admin@pravaah.demo", password: "pravaah123", role: "ADMIN", name: "System Admin" },
  {
    email: "authority@pravaah.demo",
    password: "pravaah123",
    role: "AUTHORITY",
    name: "District Authority",
  },
  {
    email: "response@pravaah.demo",
    password: "pravaah123",
    role: "RESPONSE_TEAM",
    name: "Response Team Lead",
  },
  { email: "analyst@pravaah.demo", password: "pravaah123", role: "ANALYST", name: "Risk Analyst" },
  { email: "citizen@pravaah.demo", password: "pravaah123", role: "CITIZEN", name: "Citizen User" },
] as const;

export function districtById(id: string) {
  return DISTRICTS.find((d) => d.id === id);
}
