import { cn } from "@/lib/utils";
import type { ReactNode } from "react";
import type { RiskLevel } from "@/lib/pravaah/types";

export const riskClasses: Record<RiskLevel, string> = {
  LOW: "bg-risk-low/15 text-risk-low border-risk-low/40",
  MODERATE: "bg-risk-moderate/15 text-risk-moderate border-risk-moderate/40",
  HIGH: "bg-risk-high/15 text-risk-high border-risk-high/40",
  EXTREME: "bg-risk-extreme/20 text-risk-extreme border-risk-extreme/50",
};

export const riskHex: Record<RiskLevel, string> = {
  LOW: "#2fb37a",
  MODERATE: "#e3b341",
  HIGH: "#e8863c",
  EXTREME: "#d24040",
};

export function RiskBadge({ level, score }: { level: RiskLevel; score?: number }) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-md border px-2 py-0.5 font-mono text-[11px] font-semibold tracking-widest uppercase",
        riskClasses[level],
      )}
    >
      <span className="size-1.5 rounded-full bg-current" />
      {level}
      {score !== undefined && <span className="opacity-70">· {score}</span>}
    </span>
  );
}

export function DemoBanner({ text }: { text?: string }) {
  return (
    <div className="flex items-center gap-2 rounded-md border border-risk-moderate/40 bg-risk-moderate/10 px-3 py-2 text-xs text-risk-moderate">
      <span className="font-mono font-semibold tracking-widest">DEMO / SIMULATION DATA</span>
      <span className="text-muted-foreground">
        {text ??
          "All values are synthetic and generated by the prototype model. No live government feed is connected."}
      </span>
    </div>
  );
}

export function PageHeader({
  title,
  subtitle,
  actions,
}: {
  title: string;
  subtitle?: string;
  actions?: ReactNode;
}) {
  return (
    <div className="flex flex-wrap items-end justify-between gap-3">
      <div>
        <h1 className="text-2xl font-semibold">{title}</h1>
        {subtitle && <p className="mt-1 max-w-3xl text-sm text-muted-foreground">{subtitle}</p>}
      </div>
      {actions}
    </div>
  );
}

export function Panel({
  title,
  right,
  children,
  className,
}: {
  title?: string;
  right?: ReactNode;
  children: ReactNode;
  className?: string;
}) {
  return (
    <section className={cn("panel p-4", className)}>
      {(title || right) && (
        <header className="mb-3 flex items-center justify-between gap-2">
          {title && <h2 className="label-mono">{title}</h2>}
          {right}
        </header>
      )}
      {children}
    </section>
  );
}

export function KpiCard({
  label,
  value,
  hint,
  tone = "default",
}: {
  label: string;
  value: string;
  hint?: string;
  tone?: "default" | RiskLevel;
}) {
  const toneClass =
    tone === "default"
      ? "text-foreground"
      : tone === "LOW"
        ? "text-risk-low"
        : tone === "MODERATE"
          ? "text-risk-moderate"
          : tone === "HIGH"
            ? "text-risk-high"
            : "text-risk-extreme";
  return (
    <div className="panel p-4">
      <p className="label-mono">{label}</p>
      <p className={cn("mt-2 text-3xl font-semibold tabular-nums", toneClass)}>{value}</p>
      {hint && <p className="mt-1 text-xs text-muted-foreground">{hint}</p>}
    </div>
  );
}

export function Meter({ value, level }: { value: number; level?: RiskLevel }) {
  const color =
    level === "EXTREME"
      ? "bg-risk-extreme"
      : level === "HIGH"
        ? "bg-risk-high"
        : level === "MODERATE"
          ? "bg-risk-moderate"
          : level === "LOW"
            ? "bg-risk-low"
            : "bg-primary";
  return (
    <div className="h-1.5 w-full overflow-hidden rounded-full bg-muted">
      <div className={cn("h-full rounded-full transition-all", color)} style={{ width: `${Math.min(100, Math.max(0, value))}%` }} />
    </div>
  );
}
