/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CascadeAnalysisRouteImport } from './routes/cascade-analysis'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as EvacuationRouteImport } from './routes/evacuation'
import { Route as ExposureRouteImport } from './routes/exposure'
import { Route as HistoricalEventsRouteImport } from './routes/historical-events'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as LiveMapRouteImport } from './routes/live-map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelPerformanceRouteImport } from './routes/model-performance'
import { Route as RiskAnalysisRouteImport } from './routes/risk-analysis'
import { Route as SafeRoutesRouteImport } from './routes/safe-routes'
import { Route as SatelliteRouteImport } from './routes/satellite'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CascadeAnalysisRoute = CascadeAnalysisRouteImport.update({
  id: '/cascade-analysis',
  path: '/cascade-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const EvacuationRoute = EvacuationRouteImport.update({
  id: '/evacuation',
  path: '/evacuation',
  getParentRoute: () => rootRouteImport,
} as any)
const ExposureRoute = ExposureRouteImport.update({
  id: '/exposure',
  path: '/exposure',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricalEventsRoute = HistoricalEventsRouteImport.update({
  id: '/historical-events',
  path: '/historical-events',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMapRoute = LiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelPerformanceRoute = ModelPerformanceRouteImport.update({
  id: '/model-performance',
  path: '/model-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskAnalysisRoute = RiskAnalysisRouteImport.update({
  id: '/risk-analysis',
  path: '/risk-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeRoutesRoute = SafeRoutesRouteImport.update({
  id: '/safe-routes',
  path: '/safe-routes',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteRoute = SatelliteRouteImport.update({
  id: '/satellite',
  path: '/satellite',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/cascade-analysis': typeof CascadeAnalysisRoute
  '/case-studies': typeof CaseStudiesRoute
  '/data-sources': typeof DataSourcesRoute
  '/evacuation': typeof EvacuationRoute
  '/exposure': typeof ExposureRoute
  '/historical-events': typeof HistoricalEventsRoute
  '/incidents': typeof IncidentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/live-map': typeof LiveMapRoute
  '/login': typeof LoginRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/risk-analysis': typeof RiskAnalysisRoute
  '/safe-routes': typeof SafeRoutesRoute
  '/satellite': typeof SatelliteRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/weather': typeof WeatherRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/cascade-analysis': typeof CascadeAnalysisRoute
  '/case-studies': typeof CaseStudiesRoute
  '/data-sources': typeof DataSourcesRoute
  '/evacuation': typeof EvacuationRoute
  '/exposure': typeof ExposureRoute
  '/historical-events': typeof HistoricalEventsRoute
  '/incidents': typeof IncidentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/live-map': typeof LiveMapRoute
  '/login': typeof LoginRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/risk-analysis': typeof RiskAnalysisRoute
  '/safe-routes': typeof SafeRoutesRoute
  '/satellite': typeof SatelliteRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/weather': typeof WeatherRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/cascade-analysis': typeof CascadeAnalysisRoute
  '/case-studies': typeof CaseStudiesRoute
  '/data-sources': typeof DataSourcesRoute
  '/evacuation': typeof EvacuationRoute
  '/exposure': typeof ExposureRoute
  '/historical-events': typeof HistoricalEventsRoute
  '/incidents': typeof IncidentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/live-map': typeof LiveMapRoute
  '/login': typeof LoginRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/risk-analysis': typeof RiskAnalysisRoute
  '/safe-routes': typeof SafeRoutesRoute
  '/satellite': typeof SatelliteRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/weather': typeof WeatherRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/cascade-analysis'
    | '/case-studies'
    | '/data-sources'
    | '/evacuation'
    | '/exposure'
    | '/historical-events'
    | '/incidents'
    | '/infrastructure'
    | '/live-map'
    | '/login'
    | '/model-performance'
    | '/risk-analysis'
    | '/safe-routes'
    | '/satellite'
    | '/settings'
    | '/simulation'
    | '/weather'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/cascade-analysis'
    | '/case-studies'
    | '/data-sources'
    | '/evacuation'
    | '/exposure'
    | '/historical-events'
    | '/incidents'
    | '/infrastructure'
    | '/live-map'
    | '/login'
    | '/model-performance'
    | '/risk-analysis'
    | '/safe-routes'
    | '/satellite'
    | '/settings'
    | '/simulation'
    | '/weather'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/cascade-analysis'
    | '/case-studies'
    | '/data-sources'
    | '/evacuation'
    | '/exposure'
    | '/historical-events'
    | '/incidents'
    | '/infrastructure'
    | '/live-map'
    | '/login'
    | '/model-performance'
    | '/risk-analysis'
    | '/safe-routes'
    | '/satellite'
    | '/settings'
    | '/simulation'
    | '/weather'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CascadeAnalysisRoute: typeof CascadeAnalysisRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  DataSourcesRoute: typeof DataSourcesRoute
  EvacuationRoute: typeof EvacuationRoute
  ExposureRoute: typeof ExposureRoute
  HistoricalEventsRoute: typeof HistoricalEventsRoute
  IncidentsRoute: typeof IncidentsRoute
  InfrastructureRoute: typeof InfrastructureRoute
  LiveMapRoute: typeof LiveMapRoute
  LoginRoute: typeof LoginRoute
  ModelPerformanceRoute: typeof ModelPerformanceRoute
  RiskAnalysisRoute: typeof RiskAnalysisRoute
  SafeRoutesRoute: typeof SafeRoutesRoute
  SatelliteRoute: typeof SatelliteRoute
  SettingsRoute: typeof SettingsRoute
  SimulationRoute: typeof SimulationRoute
  WeatherRoute: typeof WeatherRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cascade-analysis': {
      id: '/cascade-analysis'
      path: '/cascade-analysis'
      fullPath: '/cascade-analysis'
      preLoaderRoute: typeof CascadeAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evacuation': {
      id: '/evacuation'
      path: '/evacuation'
      fullPath: '/evacuation'
      preLoaderRoute: typeof EvacuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exposure': {
      id: '/exposure'
      path: '/exposure'
      fullPath: '/exposure'
      preLoaderRoute: typeof ExposureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historical-events': {
      id: '/historical-events'
      path: '/historical-events'
      fullPath: '/historical-events'
      preLoaderRoute: typeof HistoricalEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-map': {
      id: '/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof LiveMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-performance': {
      id: '/model-performance'
      path: '/model-performance'
      fullPath: '/model-performance'
      preLoaderRoute: typeof ModelPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-analysis': {
      id: '/risk-analysis'
      path: '/risk-analysis'
      fullPath: '/risk-analysis'
      preLoaderRoute: typeof RiskAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safe-routes': {
      id: '/safe-routes'
      path: '/safe-routes'
      fullPath: '/safe-routes'
      preLoaderRoute: typeof SafeRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite': {
      id: '/satellite'
      path: '/satellite'
      fullPath: '/satellite'
      preLoaderRoute: typeof SatelliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CascadeAnalysisRoute: CascadeAnalysisRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  DataSourcesRoute: DataSourcesRoute,
  EvacuationRoute: EvacuationRoute,
  ExposureRoute: ExposureRoute,
  HistoricalEventsRoute: HistoricalEventsRoute,
  IncidentsRoute: IncidentsRoute,
  InfrastructureRoute: InfrastructureRoute,
  LiveMapRoute: LiveMapRoute,
  LoginRoute: LoginRoute,
  ModelPerformanceRoute: ModelPerformanceRoute,
  RiskAnalysisRoute: RiskAnalysisRoute,
  SafeRoutesRoute: SafeRoutesRoute,
  SatelliteRoute: SatelliteRoute,
  SettingsRoute: SettingsRoute,
  SimulationRoute: SimulationRoute,
  WeatherRoute: WeatherRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
